/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IGBMInitiatorInterface extends ethers.utils.Interface {
  functions: {
    "getBidDecimals(uint256)": FunctionFragment;
    "getBidMultiplier(uint256)": FunctionFragment;
    "getEndTime(uint256)": FunctionFragment;
    "getHammerTimeDuration(uint256)": FunctionFragment;
    "getIncMax(uint256)": FunctionFragment;
    "getIncMin(uint256)": FunctionFragment;
    "getStartTime(uint256)": FunctionFragment;
    "getStepMin(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getBidDecimals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEndTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHammerTimeDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIncMax",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIncMin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStartTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStepMin",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getBidDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBidMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEndTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHammerTimeDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIncMax", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getIncMin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStepMin", data: BytesLike): Result;

  events: {};
}

export class IGBMInitiator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IGBMInitiatorInterface;

  functions: {
    getBidDecimals(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getBidMultiplier(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getEndTime(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getHammerTimeDuration(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getIncMax(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getIncMin(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getStartTime(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getStepMin(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  getBidDecimals(
    _auctionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getBidMultiplier(
    _auctionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getEndTime(
    _auctionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getHammerTimeDuration(
    _auctionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getIncMax(
    _auctionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getIncMin(
    _auctionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getStartTime(
    _auctionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getStepMin(
    _auctionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getBidDecimals(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBidMultiplier(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEndTime(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHammerTimeDuration(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIncMax(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIncMin(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStartTime(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStepMin(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getBidDecimals(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBidMultiplier(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEndTime(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHammerTimeDuration(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIncMax(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIncMin(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStartTime(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStepMin(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getBidDecimals(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBidMultiplier(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEndTime(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHammerTimeDuration(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIncMax(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIncMin(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStartTime(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStepMin(
      _auctionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
