/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface RealmFacetInterface extends ethers.utils.Interface {
  functions: {
    "mintParcels(address,uint32[],tuple[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "mintParcels",
    values: [
      string,
      BigNumberish[],
      {
        coordinateX: BigNumberish;
        coordinateY: BigNumberish;
        parcelId: BigNumberish;
        size: BigNumberish;
        fomoBoost: BigNumberish;
        fudBoost: BigNumberish;
        kekBoost: BigNumberish;
        alphaBoost: BigNumberish;
      }[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "mintParcels",
    data: BytesLike
  ): Result;

  events: {};
}

export class RealmFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RealmFacetInterface;

  functions: {
    mintParcels(
      _to: string,
      _tokenIds: BigNumberish[],
      _metadata: {
        coordinateX: BigNumberish;
        coordinateY: BigNumberish;
        parcelId: BigNumberish;
        size: BigNumberish;
        fomoBoost: BigNumberish;
        fudBoost: BigNumberish;
        kekBoost: BigNumberish;
        alphaBoost: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  mintParcels(
    _to: string,
    _tokenIds: BigNumberish[],
    _metadata: {
      coordinateX: BigNumberish;
      coordinateY: BigNumberish;
      parcelId: BigNumberish;
      size: BigNumberish;
      fomoBoost: BigNumberish;
      fudBoost: BigNumberish;
      kekBoost: BigNumberish;
      alphaBoost: BigNumberish;
    }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    mintParcels(
      _to: string,
      _tokenIds: BigNumberish[],
      _metadata: {
        coordinateX: BigNumberish;
        coordinateY: BigNumberish;
        parcelId: BigNumberish;
        size: BigNumberish;
        fomoBoost: BigNumberish;
        fudBoost: BigNumberish;
        kekBoost: BigNumberish;
        alphaBoost: BigNumberish;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    mintParcels(
      _to: string,
      _tokenIds: BigNumberish[],
      _metadata: {
        coordinateX: BigNumberish;
        coordinateY: BigNumberish;
        parcelId: BigNumberish;
        size: BigNumberish;
        fomoBoost: BigNumberish;
        fudBoost: BigNumberish;
        kekBoost: BigNumberish;
        alphaBoost: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    mintParcels(
      _to: string,
      _tokenIds: BigNumberish[],
      _metadata: {
        coordinateX: BigNumberish;
        coordinateY: BigNumberish;
        parcelId: BigNumberish;
        size: BigNumberish;
        fomoBoost: BigNumberish;
        fudBoost: BigNumberish;
        kekBoost: BigNumberish;
        alphaBoost: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
